CONTIKI_PROJECT = udp-client udp-server
all: $(CONTIKI_PROJECT)

APPS += powertrace collect-view
CONTIKI=../..
MAKE_MAC = MAKE_MAC_TSCH
MODULES += os/services/shell
include $(CONTIKI)/Makefile.include


